version: '3'
services:
  web:
    image: php:7.3-apache
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
      
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: someapp
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
      
volumes:
  dbdata: